import Head from 'next/head'
import NavBar from '../comps/navbar'
import Footer from '../comps/footer';
import { Text, H1 } from '../comps/global';

export default function About() {
  return (
    <div style={{display:"flex", marginTop:"100px", flexDirection:"column", alignItems:"center"}}>
      <Head>
        <title>Sandra Cleaning Service - Personalized Cleaning for your Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/sandra-logo.svg" />
      </Head>
      <NavBar/>

      <main style={{backgroundColor:"white", padding:"45px"}}>
        
        <H1 padding="0 0 20px 0">About Me</H1>
        <Text>Originally from Colombia, I am a mother of 2 children and understand how messy a house can get! After my first home in 2011, I've been determined to help out more clients to enjoy the satisfaction of coming back to a home that is spotless.</Text>
        <Text>Since families get busier, there's less time that each family has time to keep the house clean, a chore that many people find troubling, but I enjoy it, in fact, I enjoy it so much, that I don't even see it a chore! I believe my passion in transforming a home to an even better version after deep-cleaning is what makes me a great housekeeper that I've held long-term clients since the beginning.</Text>
        <Text>My favourite chore is laundry, but only when its nice and warm, I love folding them. My second favourite is sanitizing bathrooms. The bathrooms are usually the most unclean rooms in a house, not because of clutter but because of germs, I enjoy spraying sinks, toilets, tubs, and showers with my products, knowing full well those germs are gone and that makes my day better!</Text>
        <h3>One-Employee Business</h3>
        <Text>As a self-employed, I believe it calms my clients know that I'm the only one who enters their home. So, there's more personalization in specificity of what needs to be cleaned and easiness to contact with me since I'm the same person who comes back either weekly, bi-weekly, or monthly. </Text>
        <Text>I barely get sick so it's rare that I cancel or reschedule on clients. My current clients definitely rely on me that I will show up at their house on time and ready to leave the house sparkly clean!</Text>
        <h1>Products</h1>
        <Text>After a decade in working and cleaning homes, I've done my research to find strong and effective cleaning products that get the job done. </Text>
        <Text>I bring the supplies like cleaners for various surfaces, disinfectants, gloves, rags, sponges and wipes, however, I ask from my clients that if they can supply the vacuum and mop, which every house already has.</Text>
        <Text>I provide the safest products that are family-safe, however, a few of my clients provide me the products they prefer to clean with.</Text>
       
      </main>
      <Footer></Footer>
    </div>
  )
}
