import Head from 'next/head'
import NavBar from '../comps/navbar'
import { Box, Text } from '../comps/global';
import emailjs from '@emailjs/browser';
import { useRef, useState } from 'react';
import { Image } from '../comps/global';
import { motion, AnimatePresence } from "framer-motion"
import Footer from '../comps/footer';

export default function Contact() {
    const form = useRef();
    const [message, setMessage] = useState(false)

    const sendEmail = (e) => {
        e.preventDefault();

        emailjs.sendForm('service_vrogaxa', 'template_nt32eto', form.current, 'rslEA-56sdvqTTs7m')
        .then((result) => {
            console.log(result.text);
            form.current.reset();
            setMessage(true)
            setTimeout(() => {
                setMessage(false)
            }, 5000);
        }, (error) => {
            console.log(error.text);
        });
    };

  return (
    <div style={{display:"flex", flexDirection:"column", alignItems:"center"}}>
      <Head>
        <title>Sandra Cleaning Service - Personalized Cleaning for your Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/sandra-logo.svg" />
      </Head>
      <NavBar/>
      <main style={{backgroundColor:"white", padding:"45px"}}>
        {message && <AnimatePresence exitBeforeEnter>
            <motion.div  initial={{ x: 400 }} animate={{ x: 0, transition: { duration: 1, delay: 0 }}} exit={{ x: 400 }} style={{display:"flex", position:"fixed", zIndex:"15", left:"85vw", top:"100px", padding:"15px 30px", backgroundColor:"#4BDA4B", alignItems:"center", width:"fit-content"}}> 
                <Image src="/check.png" width={40} height={40} alt="checkmark" margin="0 20px 0 0"/>
                <Text padding="0px" color='white' fontWeight="600">Message Sent!</Text>
            </motion.div>
        </AnimatePresence>
        }
        
        <div className='form' style={{display:"flex", marginTop:"100px", paddingBottom:"50px", width:"100%"}}>        
            <form className='form-sections' ref={form} onSubmit={sendEmail} style={{display:"flex", flexDirection:"column", width:"50%"}}>
              <h1>Contact Form</h1>
              <Text style={{color:"#5A5A5A", padding:"0 0 25px 0", fontWeight:"500"}}>Feel free to contact me if you are interested in my services! Fill out the form below and make sure to leave a message letting me know what kind of building you'll want to be serviced (home/commericial office) and approximately how much sq/ft or floors. I will get back to you as soon as possible.</Text>
              <label>Name</label>
              <input type="text" name="user_name" style={{border:"0px", borderBottom:"1.5px solid #CCC"}} required />
              <label>Email</label>
              <input type="email" name="user_email" style={{border:"0px", borderBottom:"1.5px solid #CCC"}} required />
              <label>Message</label>
              <textarea name="message" style={{border:"1.5px solid #CCC", borderRadius:"5px", fontFamily:"'Montserrat', sans-serif"}} required/>
              <input type="submit" value="Send" style={{width:"300px", padding:"15px", backgroundColor:"#16425B", color:"white", fontSize:"16px", border:"0px", borderRadius:"10px", fontWeight:"600", cursor:"pointer", marginTop:"20px"}}/>
            </form>
            <Image className='form-sections' src="/contact.jpg" width="40%" borderRadius='10px' margin="0 0 0 10%"></Image>
        </div>
      </main>
      <Footer></Footer>
    </div>
  )
}
