import Head from 'next/head'
import NavBar from '../comps/navbar'
import Footer from '../comps/footer'
import { Hero, H1, H2, H3, H4, Text, Box, PullQuote, Image, Container, CTA } from '../comps/global'
import Card from '../comps/card'
import Testimonial from '../comps/testimonial'
import { Swiper, SwiperSlide } from 'swiper/react';
import SwiperCore, { Navigation, Pagination } from 'swiper'
import 'swiper/swiper-bundle.css'
import 'swiper/css';
SwiperCore.use([Navigation, Pagination])
import styled from 'styled-components'
import { useRouter } from 'next/router'

const Ita = styled.i`
  display:inline;
  width:300px;
  padding:0;
  margin:0;
  height:fit-content
`


export default function Home() {

  const r = useRouter()

  return (
    <div style={{display:"flex", flexDirection:"column", alignItems:"center"}}>
      <Head>
        <title>She's A Keeper- Personalized Cleaning for your Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/sandra-logo.svg" />
      </Head>

      <NavBar />

      <main>
        <Hero className="hero" padding="calc(75px + 15%) 0" src="/hero.svg" margin="90px 0 0 0" width="100%">
          <H1 width="calc(100px + 45%)" marginTop="-100px">A Clean Home is a Happy Home</H1>
        </Hero>

        <Container height="fit-content" aliIt="center" flexDir="column" bgColor="white">
        <PullQuote><i>"Having a clean home is one of the many ways that keeps you and your family's lives simpler and I do my best to achieve my client's satisfaction."</i></PullQuote>
        <H2 textAlign="center">Ready for a Stress-Free Living?</H2>
        <Box justCont="center" padding="10px 0 50px 0">
          <CTA onClick={()=>{r.push("/services")}}>Learn about my services</CTA>
        </Box>
        <H4 color="#16425B" padding="10px 70px" fontWeight="500">Sandra Arango, self-employed and owner of <Ita>She's A Keeper</Ita> is happy to help out in keeping your house clean and tidy within the Tri-Cities (Coquitlam, Port Coquitlam, and Port Moody) and Pitt Meadows.</H4>
        <H4 color="#16425B" padding="10px 70px" fontWeight="500">What makes <Ita>She's A Keeper</Ita> stand out is the personalized cleaning, where my clients get a free quote for the first visit that allows me to speak with my new client and make sure where they would like me to prioritize my cleaning or make special requests for example to do the laundry on cleaning visits.</H4>
        <H4 color="#16425B" padding="10px 70px" fontWeight="500">I also welcome feedback to make sure my clients are satisfied and happy with the cleaning, making it a win-win since I'm happy when my clients are happy. As a member of the Tri-City community I'm serving, it brings me happiness that I can give back with helping out its members.</H4>
        <H4 color="#16425B" padding="10px 70px" fontWeight="500">Since <Ita>She's A Keeper</Ita> is a self-employed cleaning service with one housekeeper, you can be sure you will getting the consistent cleaning you expect and the security of having the same housekeeper making sure your home is neat and tidy.</H4>
        </Container>

        <Container height="fit-content" aliIt="center" flexDir="column" padding="0px 0px 40px 0px" bgColor="white">
          <H2 padding="75px 0px 30px 0px" textAlign="center">Why Choose <i>She's A Keeper?</i></H2>
          <Box className="reason" width="85%" margin="0 0 -150px" justCont="space-between">
            <Card widthImg="60%" heading="Flexible Schedule" paragraph="Adapt if client wants a weekly, bi-weekly, and monthly recurring cleaning" src="/flexibleIcon.svg"></Card>
            <Card widthImg="60%" heading="Affordable Pricing" paragraph="Determine what your necessary house cleaning needs are to estimate an accurate fair price." src="/priceIcon.svg"></Card>
            <Card widthImg="60%" heading="Listen Feedback" paragraph="Communicate if clients are beyond satisfied with the service and adapt to your feedback" src="/feedbackIcon.svg"></Card>
          </Box>
        </Container>

        <Container height="fit-content" flexDir="column" padding="50px 0px" margin="0 0 -150px 0" bgColor="#2F6690">
          <H2 color='white' padding="175px 0px 20px 0px" textAlign="center" width="100%">Experience Statistics</H2>
          <H3 color='#C8F8FA' padding="0px" textAlign="center" width="100%">As of 2022, I have</H3>
          <Box height="fit-content" flexWrap="wrap" justCont="center" width="100%">
            <Box className='stat' minHeight="155px" width="55%" bgColor="#16425B" aliIt="center" justCont="center" borderRadius="10px 0 0 0" padding="20px">
              <Image src="/reward.svg" width="110px" padding="5px"></Image>
              <Box width="80%" aliIt="center" flexDir="column" padding="0px">
                <H1 fSize="35px" color="#81C3D7" padding="0px">12</H1>
                <H4 padding="0px" color="#81C3D7" textAlign="center">Years of Residential Cleaning</H4>
              </Box>
            </Box>
            <Box className='stat' minHeight="155px" width="30%" bgColor="#81C3D7" aliIt="center" justCont="center" borderRadius="0 10px 0 0" padding="20px">
              <Image src="/clients.svg" width="110px" padding="10px"></Image>
              <Box width="80%" aliIt="center" flexDir="column" padding="0px">
                <H1 fSize="35px" padding="0px" color="white">21</H1>
                <H4 padding="0px" color="white" textAlign="center">Satisfied Clients</H4>
              </Box>
            </Box>
            <Box className='stat' minHeight="155px" width="85%" bgColor="#F5F5F5" aliIt="center" justCont="center" padding="20px">
              <Image src="/house.svg" width="110px" padding="10px"></Image>
              <Box width="80%" aliIt="center" flexDir="column" padding="0px">
                <H1 color="#16425B" fSize="35px" padding="0px">6000+</H1>
                <H4 padding="0px" color="#16425B" textAlign="center">House Cleanings</H4>
              </Box>
            </Box>
            <Box className='stat' minHeight="155px" width="42.5%" bgColor="#81C3D7" aliIt="center" justCont="center" borderRadius="0 0 0 10px" padding="20px">
              <Image src="/commercial.svg" height="110px" padding="10px"></Image>
              <Box width="80%" aliIt="center" flexDir="column" padding="0px">
                <H1 fSize="35px" padding="0px" color="white">3</H1>
                <H4 padding="0px" color="white" textAlign="center">Commercial Locations</H4>
              </Box>
            </Box>
            <Box className='stat' minHeight="155px" width="42.5%" bgColor="#16425B" aliIt="center" justCont="center" borderRadius="0 0 10px 0" padding="20px">
              <Image src="/satisfaction.svg" width="110px" padding="10px"></Image>
              <Box width="80%" aliIt="center" flexDir="column" padding="0px" margin="0px 20px">
                <H1 fSize="35px" padding="0px" color='#81C3D7'>100%</H1>
                <H4 padding="0px" color="#81C3D7" textAlign="center">Satisfaction Guaranteed</H4>
              </Box>
            </Box>
          </Box>
        </Container>

        <Container height="fit-content" aliIt="center" flexDir="column" padding="50px 0px" bgColor="white">
          <H2 padding="175px 0px 20px 0px" textAlign="center">Testimonials</H2>
          <H3 color='#2F6690' padding="0px" textAlign="center">This is what customers have to say about <i><strong>She's A Keeper</strong></i></H3>
          <Box>
            <Swiper navigation pagination>
              <SwiperSlide>
                <Box justCont="center" padding="20px 70px 50px 70px" width="100%">
                  <Testimonial classs="testimonial" heading="- Mitsy Jackson, a client for 6 years" paragraph="Adapt if client wants a weekly, bi-weekly, and monthly recurring cleaning" src="/flexibleIcon.svg"></Testimonial>
                </Box>
              </SwiperSlide>
              <SwiperSlide>
                <Box justCont="center" padding="20px 70px 50px 70px" width="100%">
                  <Testimonial classs="testimonial" heading="Affordable Pricing" paragraph="Determine what your necessary house cleaning needs are to estimate an accurate fair price." src="/priceIcon.svg"></Testimonial>
                </Box>
              </SwiperSlide>
              <SwiperSlide>
                <Box justCont="center" padding="20px 70px 50px 70px" width="100%">
                  <Testimonial classs="testimonial" heading="Listen Feedback" paragraph="Communicate if clients are beyond satisfied with the service and adapt to your feedback" src="/feedbackIcon.svg"></Testimonial>
                </Box>
              </SwiperSlide>
            </Swiper>
          </Box>
        </Container>
      </main>

      <Footer></Footer>
      
    </div>
  )
}
