import Head from 'next/head'
import NavBar from '../comps/navbar'
import { Hero, H1, Box } from '../comps/global'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Sandra Cleaning Service - Personalized Cleaning for your Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/sandra-logo.svg" />
      </Head>

      <main>
        <NavBar/>
        <Hero className="hero" src="/hero.jpeg" width="100vw">
          <H1 padding="15% 0 0 5%">Clean Home. <br/> Happy Home.</H1>
        </Hero>

      </main>
    </div>
  )
}
