import Head from 'next/head'
import NavBar from '../comps/navbar'
import Footer from '../comps/footer'
import { Hero, H1, H2, H3, H4, Box, PullQuote, Image, Container } from '../comps/global'
import Card from '../comps/card'
import Testimonial from '../comps/testimonial'
import { useEffect, useState, useRef } from 'react'
import { Swiper, SwiperSlide } from 'swiper/react';
import SwiperCore, { Navigation, Pagination } from 'swiper'
import 'swiper/swiper-bundle.css'
import 'swiper/css';
import {Loader} from '@googlemaps/js-api-loader';
SwiperCore.use([Navigation, Pagination])

export default function Home() {
  // const [cardWidth, setCardWidth] = useState("150px")
  // const [cardJustCont, setCardJustCont] = useState("")
  // function OnLoad(){
  //   useEffect(() => {
  //     var Boxy = document.querySelector(".Reason")
  //     window.addEventListener("resize", function() {
  //       if(window.innerWidth < 850){
  //         Boxy.style.flexDirection = "column";
  //         // console.log(window.innerWidth);
  //         setCardWidth("80vw")
  //         setCardJustCont("center")
  //       } else {
  //         Boxy.style.flexDirection = "row";
  //         setCardWidth("150px")
  //         setCardJustCont("")
  //       }  
  //     });
  //   });
  // }

  // const googlemap = useRef(null);
  // useEffect(() => {
  //   const loader = new Loader({
  //     apiKey:process.env.NEXT_PUBLIC_API_KEY,
  //     version: 'weekly',
  //   });
  //   let map; 
  //   loader.load().then(() => {
  //     const google = window.google;
  //     map = new google.maps.Map(googlemap.current, {
  //       center: {lat: -34.397, lng: 150.644},
  //       zoom: 8,
  //     });
  //   });
  // });

  return (
    <div>
      <Head>
        <title>She's A Keeper- Personalized Cleaning for your Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/sandra-logo.svg" />
      </Head>

      <main>
        <NavBar />
        <Hero className="hero" padding="calc(75px + 15%) 0 calc(75px + 15%) 5%" src="/clean.jpeg" width="100vw" margin="90px 0 0 0" height="fit-content"></Hero>
        <H1 width="calc(100px + 45%)" bgColor="rgba(221,230,213,0.85)" padding="calc(40px + 1%) 5% calc(40px + 1%) 5%" margin="-100px 0 0 0" borderRadius="0 30px 30px 0">Clean Home. <br /> Happy Home.</H1>
        <PullQuote><i>"Having a clean home is one of the many ways that keeps you and your family's lives simpler and I do my best to achieve my client's satisfaction."</i></PullQuote>
        <H2>Ready for a stress-free clean?</H2>
        <button>Learn about my services</button>
        <H3>Sandra Arango, self-employed and owner of <i>She's A Keeper</i> is happy to help out in keeping your house clean and tidy within the Tri-Cities (Coquitlam, Port Coquitlam, and Port Moody) and Pitt Meadows. </H3>
        <H3>What makes <i>She's A Keeper</i> stand out is the personalized cleaning, where my clients get a free quote for the first visit that allows me to speak with my new client and make sure where they would like me to prioritize my cleaning or make special requests for example to do the laundry on cleaning visits.</H3>
        <H3>I also welcome feedback to make sure my clients are satisfied and happy with the cleaning, making it a win-win since I'm happy when my clients are happy. As a member of the Tri-City community I'm serving, it brings me happiness that I can give back with helping out its members</H3>
        <H3>Since <i>She's A Keeper</i> is a self-employed cleaning service with one housekeeper, you can be sure you will getting the consistent cleaning you expect and the security of having the same housekeeper making sure your home is neat and tidy</H3>
        {/* <div id="map" ref={googlemap}></div> */}

        <Container height="fit-content" aliIt="center" flexDir="column" padding="0px 0px 40px 0px">
          <H2 padding="75px 0px 30px 0px" textAlign="center" width="100vw">Why Choose <i>She's A Keeper?</i></H2>
          <Box className="reason" width="85vw" margin="0 0 -150px" justCont="space-between">
            <Card heading="Flexible Schedule" paragraph="Adapt if client wants a weekly, bi-weekly, and monthly recurring cleaning" src="/flexibleIcon.svg"></Card>
            <Card heading="Affordable Pricing" paragraph="Determine what your necessary house cleaning needs are to estimate an accurate fair price." src="/priceIcon.svg"></Card>
            <Card heading="Listen Feedback" paragraph="Communicate if clients are beyond satisfied with the service and adapt to your feedback" src="/feedbackIcon.svg"></Card>
          </Box>
        </Container>

        <Container height="fit-content" aliIt="center" flexDir="column" padding="50px 0px" margin="0 0 -150px 0" bgColor="#2F6690">
          <H2 color='white' padding="175px 0px 20px 0px" textAlign="center" width="100vw">Experience Statistics</H2>
          <H3 color='#C8F8FA' padding="0px" textAlign="center" width="100vw">As of 2022, I have</H3>
          <Box width="85vw" height="fit-content" flexWrap="wrap">
            <Box minHeight="220px" width="55vw" bgColor="#F5F5F5" aliIt="center" justCont="center" borderRadius="10px 0 0 0">
              <Image src="/reward.svg" width="calc(75px + 15%)" padding="20px"></Image>
              <Box width="calc(50px + 35%)" aliIt="center" flexDir="column" padding="0px">
                <H1 fSize="calc(10px + 7vw)" padding="0px">12</H1>
                <H4 padding="0px" color="#16425B" textAlign="center">Years of Residential Cleaning</H4>
              </Box>
            </Box>
            <Box minHeight="220px" width="30vw" bgColor="#81C3D7" aliIt="center" justCont="center" borderRadius="0 10px 0 0">
              <Image src="/clients.svg" width="calc(75px + 20%)" padding="20px"></Image>
              <Box width="calc(50px + 35%)" aliIt="center" flexDir="column" padding="0px">
                <H1 fSize="calc(10px + 7vw)" padding="0px">21</H1>
                <H4 padding="0px" color="#16425B" textAlign="center">Satisfied Clients</H4>
              </Box>
            </Box>
            <Box minHeight="220px" width="85vw" bgColor="#16425B" aliIt="center" justCont="center">
              <Image src="/house.svg" width="calc(75px + 10%)" padding="20px"></Image>
              <Box width="calc(50px + 35%)" aliIt="center" flexDir="column" padding="0px">
                <H1 color="white" fSize="calc(10px + 7vw)" padding="0px">6000+</H1>
                <H4 padding="0px" color="white" textAlign="center">House Cleanings</H4>
              </Box>
            </Box>
            <Box minHeight="220px" width="42.5vw" bgColor="#81C3D7" aliIt="center" justCont="center" borderRadius="0 0 0 10px">
              <Image src="/commercial.svg" width="calc(75px + 13%)" padding="20px"></Image>
              <Box width="calc(50px + 35%)" aliIt="center" flexDir="column" padding="0px">
                <H1 fSize="calc(10px + 7vw)" padding="0px">3</H1>
                <H4 padding="0px" color="#16425B" textAlign="center">Commercial Locations</H4>
              </Box>
            </Box>
            <Box minHeight="220px" width="42.5vw" bgColor="#F5F5F5" aliIt="center" justCont="center" borderRadius="0 0 10px 0" padding="0">
              <Image src="/satisfaction.svg" width="calc(75px + 12%)" padding="0 20px 0 0"></Image>
              <Box width="fit-content" aliIt="center" flexDir="column" padding="0px">
                <H1 fSize="calc(10px + 7vw)" padding="0px">100%</H1>
                <H4 padding="0px" color="#16425B" textAlign="center">Satisfaction Guaranteed</H4>
              </Box>
            </Box>
          </Box>
        </Container>

        <Container height="fit-content" aliIt="center" flexDir="column" padding="50px 0px" bgColor="#DDE6D5">
          <H2 padding="175px 0px 20px 0px" textAlign="center" width="100vw">Testimonials</H2>
          <H3 color='#2F6690' padding="0px" textAlign="center" width="100vw">This is what customers have to say about <i><strong>She's A Keeper</strong></i></H3>
          <Box width="85vw">
            <Swiper navigation pagination>
              <SwiperSlide>
                <Box justCont="center" padding="20px 0 50px 0" width="85vw">
                  <Testimonial classs="testimonial" heading="- Mitsy Jackson, a client for 6 years" paragraph="Adapt if client wants a weekly, bi-weekly, and monthly recurring cleaning" src="/flexibleIcon.svg"></Testimonial>
                </Box>
              </SwiperSlide>
              <SwiperSlide>
                <Box justCont="center" padding="20px 0 50px 0" width="85vw">
                  <Testimonial classs="testimonial" heading="Affordable Pricing" paragraph="Determine what your necessary house cleaning needs are to estimate an accurate fair price." src="/priceIcon.svg"></Testimonial>
                </Box>
              </SwiperSlide>
              <SwiperSlide>
                <Box justCont="center" padding="20px 0 50px 0" width="85vw">
                  <Testimonial classs="testimonial" heading="Listen Feedback" paragraph="Communicate if clients are beyond satisfied with the service and adapt to your feedback" src="/feedbackIcon.svg"></Testimonial>
                </Box>
              </SwiperSlide>
            </Swiper>
          </Box>
        </Container>
        <Footer></Footer>
      </main>
    </div>
  )
}
