import Head from 'next/head'
import NavBar from '../comps/navbar'
import Footer from '../comps/footer'
import { Hero, H1, H2, H3, H4, Text, Box, PullQuote, Image, Container } from '../comps/global'
import Card from '../comps/card'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Sandra Cleaning Service - Personalized Cleaning for your Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/sandra-logo.svg" />
      </Head>

      <main>
        <NavBar/>
        <Hero src="/laundry.jpg" width="60vw" margin="90px 0 0 0" height="35vw" bgSize="cover"></Hero>
        <Hero src="/vacuum.jpg" width="60vw" height="35vw" zIndex="1" position="absolute" top="130px" right="0px" bgSize="cover" bgPosition="center top" transform="scaleX(-1)"></Hero>
        <H1 width="calc(100px + 45%)" position="absolute" bgColor="rgba(221,230,213,0.85)" padding="calc(40px + 1%) 5% calc(40px + 1%) 5%" margin="-100px 0 0 0" borderRadius="0 30px 30px 0" zIndex="2">Services</H1>
        <Box bgColor="red" padding="250px 0 0 0" justCont="center">
          <Box width="80vw" justCont="space-between" flexWrap="wrap">
            <Card show="" maxWidth='235px' minHeight='235px' margin="10px"></Card>
            <Card show="" maxWidth='235px' minHeight='235px' margin="10px"></Card>
            <Card show="" maxWidth='235px' minHeight='235px' margin="10px"></Card>
            <Card show="" maxWidth='235px' minHeight='235px' margin="10px"></Card>
          </Box>
          
        </Box>
        

      </main>
    </div>
  )
}
